# Generated by Django 3.0.5 on 2020-04-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LED_FROM',
            fields=[
                ('switch', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
