# Generated by Django 3.0.5 on 2020-04-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LED_FROM',
            new_name='LED_FORM',
        ),
    ]
